### ISSUE TITLE
what does this plugin do

### ISSUE THREAD

**Issue by ghost** [geel9/runelite-custom-item-hovers#3]
-

**Comment by geel9** [comment]
It allows you to define custom hover text that appears when your mouse hovers over items.

I mainly released the plugin so that I could install it on my own RuneLite installation; beyond ensuring that it continues to function, I don't really have time to prioritize making it as attractive as possible to as many people as possible. 

I encourage you to [read the documentation](https://github.com/geel9/runelite-custom-item-hovers/blob/master/docs/HoverFiles.md), which does include some pictures.
